ALTER TABLE donor
    ADD COLUMN email VARCHAR(300) DEFAULT NULL,
    ADD COLUMN street_address VARCHAR(160) DEFAULT NULL,
    ADD COLUMN number_address INT DEFAULT NULL,
    ADD COLUMN details_address VARCHAR(160) DEFAULT NULL,
    ADD COLUMN nb_address VARCHAR(160) DEFAULT NULL,
    ADD COLUMN cep VARCHAR(8) DEFAULT NULL;
